// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCMffd-MBADiC8uzqLpYLyPy_h6__sFA',
    appId: '1:627758136559:web:84bee29752fb177ba5ef1a',
    messagingSenderId: '627758136559',
    projectId: 'pocket-pokedex-8e2e0',
    authDomain: 'pocket-pokedex-8e2e0.firebaseapp.com',
    storageBucket: 'pocket-pokedex-8e2e0.firebasestorage.app',
    measurementId: 'G-EC3PED1R4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7L0MflzFPN0rIk_0HlSxpnnzuePR624',
    appId: '1:627758136559:android:117a4e4d45c83d7da5ef1a',
    messagingSenderId: '627758136559',
    projectId: 'pocket-pokedex-8e2e0',
    storageBucket: 'pocket-pokedex-8e2e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenUBS6udOdy8vOYd7pSZieXah01nrh6Y',
    appId: '1:627758136559:ios:79576e6a60e3811ca5ef1a',
    messagingSenderId: '627758136559',
    projectId: 'pocket-pokedex-8e2e0',
    storageBucket: 'pocket-pokedex-8e2e0.firebasestorage.app',
    iosBundleId: 'com.example.pocketPokedex',
  );
}
